# Generated by Django 4.2.6 on 2023-11-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('repeatpassword', models.ImageField(blank=True, null=True, upload_to='PRODUCT')),
                ('email', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
