# Generated by Django 4.2.6 on 2023-11-27 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginDb',
            new_name='signupDb',
        ),
    ]
