# Generated by Django 4.2.6 on 2023-11-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_logindb_signupdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdb',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signupdb',
            name='repeatpassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
