# Generated by Django 4.2.6 on 2023-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_booktabledb_remove_signupdb_repeatpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktabledb',
            name='persons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
