# Generated by Django 4.2.6 on 2023-12-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_booktabledb_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
