# Generated by Django 4.2.6 on 2023-12-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_formfillingdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfillingdb',
            name='payment',
        ),
    ]
