# Generated by Django 4.2.6 on 2023-12-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_remove_formfillingdb_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
