# Generated by Django 5.0 on 2024-02-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_cartdb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
