# Generated by Django 5.0 on 2024-02-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_signupdb_address_signupdb_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
