# Generated by Django 5.0 on 2024-02-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_signupdb_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('qty', models.IntegerField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
