# Generated by Django 5.0 on 2024-02-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=100, null=True),
        ),
    ]
