# Generated by Django 5.0 on 2024-02-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_alter_checkout_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
