# Generated by Django 5.0.1 on 2024-03-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_checkout_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktabledb',
            name='fromtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booktabledb',
            name='totime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='booktabledb',
            unique_together={('date', 'fromtime', 'totime')},
        ),
    ]
