# Generated by Django 5.0.1 on 2024-03-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_checkout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
