# Generated by Django 4.2.6 on 2023-11-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(blank=True, max_length=100, null=True)),
                ('productcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('productimg', models.ImageField(blank=True, null=True, upload_to='')),
                ('productprice', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
