# Generated by Django 4.2.6 on 2023-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_addproductdb_productimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproductdb',
            name='productdescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
