# Generated by Django 5.0 on 2024-02-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_addproductdb_productdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(blank=True, max_length=150, null=True)),
                ('capacity', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
